using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;
using System.Data.SqlClient;

namespace ZCZJ_DPF.TM_Data
{
    public partial class TM_Out_Old_View : System.Web.UI.Page
    {
        string sqlText;
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                InitInfo();
            }
        }
        private void InitInfo()
        {
            string action = Request.QueryString["action"];
            string sqltxt = "select OST_STATE from TBPM_OUTSCHANGERVW where OST_CHANGECODE='" + action + "'";
            SqlDataReader dr = DBCallCommon.GetDRUsingSqlText(sqltxt);
            if (dr.Read())
            {
                if (dr[0].ToString() == "8")
                {
                    sqlText = "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_TOTALWGHTL,OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE (OSL_MARID is null or OSL_MARID='') AND OSL_OUTSOURCECHGNO='" + action + "'";
                    sqlText += " UNION ALL ";
                    sqlText += "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,'N' as OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL>0 AND OSL_FIXEDSIZE='N' AND OSL_OUTSOURCECHGNO='" + action + "' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " UNION ALL ";
                    sqlText += "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,'Y' as OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL>0 AND OSL_FIXEDSIZE='Y' AND OSL_OUTSOURCECHGNO='" + action + "' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " UNION ALL ";
                    sqlText += " select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL=0 AND OSL_OUTSOURCECHGNO='" + action + "' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " order by OSL_MARID";
                }
                else
                {
                    sqlText = "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_TOTALWGHTL,OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE (OSL_MARID is null or OSL_MARID='') AND OSL_NEWXUHAO in (select OSL_OLDXUHAO from TBPM_OUTSCHANGE where OST_CHANGECODE='" + action + "') and OSL_STATUS='0'";
                    sqlText += " UNION ALL ";
                    sqlText += "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,'N' as OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL>0 AND OSL_FIXEDSIZE='N' AND OSL_NEWXUHAO in (select OSL_OLDXUHAO from TBPM_OUTSCHANGE where OST_CHANGECODE='" + action + "') and OSL_STATUS='0' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " UNION ALL ";
                    sqlText += "select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,'Y' as OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL>0 AND OSL_FIXEDSIZE='Y' AND OSL_NEWXUHAO in (select OSL_OLDXUHAO from TBPM_OUTSCHANGE where OST_CHANGECODE='" + action + "') and OSL_STATUS='0' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " UNION ALL ";
                    sqlText += " select OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,SUM(OSL_TOTALWGHTL)AS OSL_TOTALWGHTL,SUM(OSL_NUMBER)AS OSL_NUMBER,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE from View_TM_OUTSOURCELIST WHERE OSL_MARID!='' and OSL_TOTALWGHTL=0 AND OSL_NEWXUHAO in (select OSL_OLDXUHAO from TBPM_OUTSCHANGE where OST_CHANGECODE='" + action + "') and OSL_STATUS='0' group by OSL_OUTSOURCECHGNO,OSL_TRACKNUM,OSL_MARID,OSL_NAME,OSL_GUIGE,OSL_CAIZHI,OSL_UNITWGHT,OSL_KEYCOMS,OSL_FIXEDSIZE,OSL_WDEPNAME,OSL_REQUEST,OSL_REQDATE,OSL_DELSITE ";
                    sqlText += " order by OSL_MARID";
                }
            }
            dr.Close();
            DBCallCommon.BindGridView(GridView1, sqlText);
        }
    }
}
